services:
  postgres:
    image: postgres:18-alpine
    container_name: erp-db
    restart: unless-stopped
    environment:
      # The Superuser (Use this for your manual setup/migrations)
      POSTGRES_USER: erp_admin
      POSTGRES_PASSWORD: -SuperErp@Postgres2026
      # The specific database name for your ERP
      POSTGRES_DB: super_erp
    volumes:
      # Persistent data storage for your Ubuntu host
      - postgres_data:/var/lib/postgresql/data
    networks:
      - erp-network
    healthcheck:
      # Matches the user and DB defined above
      test: ["CMD-SHELL", "pg_isready -U erp_admin -d super_erp"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  erp-network:
    name: erp-shared-network
    driver: bridge

volumes:
  # Docker will manage this volume in /var/lib/docker/volumes/
  postgres_data:
    driver: local